### ISSUE TITLE
Doesn't compile using recent kernel sources

### ISSUE THREAD

**Issue by jfrickson** [lwfinger/rtl8190p#5]
Getting errors such as the following

```
/srv/Downloads/Devices/NIC/rtl8190p-master/src/rtl_core.c:2577:10: error: ‘struct net_device’ has no member named ‘trans_start’; did you mean ‘mem_start’?
     dev->trans_start = jiffies;
        ^~
/srv/Downloads/Devices/NIC/rtl8190p-master/src/rtllib_rx.c:1017:5: error: ‘struct net_device’ has no member named ‘last_rx’
  dev->last_rx = jiffies;
     ^~
/srv/Downloads/Devices/NIC/rtl8190p-master/src/rtllib_crypt_tkip.c:119:25: error: implicit declaration of function ‘crypto_alloc_hash’; did you mean ‘crypto_alloc_base’? [-Werror=implicit-function-declaration]
  priv->tx_tfm_michael = crypto_alloc_hash("michael_mic", 0,
                         ^~~~~~~~~~~~~~~~~
/srv/Downloads/Devices/NIC/rtl8190p-master/src/rtllib_crypt_tkip.c:162:4: error: implicit declaration of function ‘crypto_free_hash’; did you mean ‘crypto_free_comp’? [-Werror=implicit-function-declaration]
    crypto_free_hash(priv->tx_tfm_michael);
    ^~~~~~~~~~~~~~~~
/srv/Downloads/Devices/NIC/rtl8190p-master/src/rtllib_crypt_tkip.c:684:13: error: implicit declaration of function ‘crypto_hash_setkey’; did you mean ‘crypto_cipher_setkey’? [-Werror=implicit-function-declaration]
         if (crypto_hash_setkey(tfm_michael, key, 8))
             ^~~~~~~~~~~~~~~~~~
/srv/Downloads/Devices/NIC/rtl8190p-master/src/rtllib_crypt_tkip.c:689:16: error: implicit declaration of function ‘crypto_hash_digest’; did you mean ‘crypto_has_cipher’? [-Werror=implicit-function-declaration]
         return crypto_hash_digest(&desc, sg, data_len + 16, mic);
                ^~~~~~~~~~~~~~~~~~

```

**Comment by ARao0123** [comment]
@jfrickson : Did you find a solution to this issue? Even I'm having the same errors.

**Comment by jfrickson** [comment]
@amrithathorath No, I didn't. Gave up on it.

**Comment by lwfinger** [comment]
Sorry that it took me so long to get to this. I lost track of the original post.

The repo has been updated to build on kernels as new as v5.6. Unfortunately, I do not have one of these devices, thus the changes have only been build tested.

Be aware that the Makefile has been completely rewritten. Do NOT do a 'cd src && make'. Just do 'make && sudo make install' from the base directory.
