### ISSUE TITLE
Building for Old Kernel Fails

### ISSUE THREAD

**Issue by Crono141** [lwfinger/rtl8190p#8]
I have an old PC I am trying to re-purpose, and I've install LinuxCNC on it.  This is a debian flavor with kernel version 4.19.0-16-rt-amd64. This machine has an RTL8190 wireless PCI card in it, which I am trying to get operational.  I've gone down the ndiswrapper route with no luck, and discovered this driver source.  Upon trying to make, I get the following warning:

`rtl8190p/src/rtllib_crypt_tkip.c: In function ‘rtllib_tkip_init’:
/home/joe/rtl8192du/rtl8190p/src/rtllib_crypt_tkip.c:122:22: error: implicit declaration of function ‘crypto_alloc_sync_skcipher’; did you mean ‘crypto_alloc_skcipher’? [-Werror=implicit-function-declaration]
  priv->tx_tfm_arc4 = crypto_alloc_sync_skcipher("ecb(arc4)", 0,
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
`
Followed by a good number of similar errors (implicit declaration of functions), and a good many more warning related to those same functions.  I am able to build the rtl8192du driver (though it doesn't work with the hardware I have), so I have all the build essentials it seems.  Can you please assist?

**Comment by Crono141** [comment]
Here's the offending code block:

#if (LINUX_VERSION_CODE < KERNEL_VERSION(4, 3, 0))
	priv->tx_tfm_arc4 = crypto_alloc_blkcipher("ecb(arc4)", 0,
			CRYPTO_ALG_ASYNC);
#else
	priv->tx_tfm_arc4 = crypto_alloc_sync_skcipher("ecb(arc4)", 0,
			CRYPTO_ALG_ASYNC);
#endif

My kernel is less than version 4.3.0, so it shouldn't even be executing the offending statement.  Is this expected behavior?

EDIT: Actually, in most circles, 19 > 3, so I guess I am greater than 4.3.0.   So the offending code should be executed, so I still need to correct the compile error.

**Comment by lwfinger** [comment]
No. Please run the command
grep -r LINUX_VERSION_CODE /lib/modules/$(uname -r)/build/include
and post the result.

**Comment by Crono141** [comment]
/lib/modules/4.19.0-16-rt-amd64/build/include/generated/uapi/linux/version.h:#define LINUX_VERSION_CODE 267189

**Comment by Crono141** [comment]
Actually, in most circles, 19 > 3, so I guess I am greater than 4.3.0. So the offending code should be executed, so I still need to correct the compile error.

**Comment by lwfinger** [comment]
That code converts to 4.19.181.

I did a little bit of operations on my source with git. crypto_alloc_blkcipher() was removed in kernel 5.5, thus that test should be 

#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 5, 0))

I fixed several of the tests in that routine. Do a 'git pull' and try again.

**Comment by Crono141** [comment]
Thanks. New Errors.

/home/joe/rtl8192du/rtl8190p/src/rtllib_crypt_tkip.c: In function ‘rtllib_tkip_init’:
/home/joe/rtl8192du/rtl8190p/src/rtllib_crypt_tkip.c:122:20: error: assignment to ‘struct crypto_sync_skcipher *’ from incompatible pointer type ‘struct crypto_blkcipher *’ [-Werror=incompatible-pointer-types]
  priv->tx_tfm_arc4 = crypto_alloc_blkcipher("ecb(arc4)", 0,

**Comment by lwfinger** [comment]
I think I fixed that one. Do another pull.

**Comment by Crono141** [comment]
Alright, here's the full error messages.
[make.log](https://github.com/lwfinger/rtl8190p/files/6407570/make.log)

**Comment by lwfinger** [comment]
I found a missing include and a couple of bad tests. Please try again. Your make.log was very useful. Perhaps we can continue to get more than 1 bug per cycle. :)

**Comment by Crono141** [comment]
Thanks, here's the next one.
[make.log](https://github.com/lwfinger/rtl8190p/files/6408038/make.log)

**Comment by lwfinger** [comment]
I figured out how to get a 4.19 kernel on my system. It does not run, but all the include files are correct.

The version I just pushed will build on 4.19 to 5.12+. I hope it works.

**Comment by Crono141** [comment]
Got one more error.  Thanks for all the effort!
[make.log](https://github.com/lwfinger/rtl8190p/files/6410183/make.log)

**Comment by lwfinger** [comment]
I just pushed a fix for that. Perhaps this one will work.

**Comment by Crono141** [comment]
[dmesg.log](https://github.com/lwfinger/rtl8190p/files/6410309/dmesg.log)
Awesome.  It now builds and installs.  But for some reason the hardware is still using the wrong driver (which doesn't work).  I tried blacklisting the incorrect driver, but that had no effect.  I know we're into general linux troubleshooting now, so I understand if you don't want to continue to help, but I'm not sure how to proceed now.

lspic -nnc:
04:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. RTL8190 802.11n PCI Wireless Network Adapter [10ec:8190]
	Subsystem: Realtek Semiconductor Co., Ltd. RTL8190 802.11n PCI Wireless Network Adapter [10ec:8190]
	Flags: bus master, medium devsel, latency 64, IRQ 16
	I/O ports at dc00 [size=256]
	Memory at f76ff000 (32-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: **rtl819xP**
	Kernel modules: **8190p**

lsmod | grep 819:
8190p                 372736  1

/etc/modprobe.d/blacklist:
blacklist rtl819xP
blacklist wl

Thanks again for your help.

EDIT: Also, when I modprobe 8190p, the terminal hangs/no return.

**Comment by lwfinger** [comment]
This driver was named rtl819xP. I changed it internally. You are getting the right driver, no matter the name.
To help with the hang when you modprobe 8190p, have a second, visible terminal running 'dmesg -w'. That way we can catch any error messages.

**Comment by Crono141** [comment]
If you check my comment again, I added in the DMESG from boot.  It seems theres a problem that starts around 11.005920

[   11.005916] rtllib_crypt: registered algorithm 'NULL'
[   11.005917] rtllib_crypt: registered algorithm 'TKIP'
[   11.005918] rtllib_crypt: registered algorithm 'CCMP'
[   11.005919] rtllib_crypt: registered algorithm 'WEP'
[   11.005920] 
               Linux kernel driver for RTL8192 based WLAN cards
[   11.005920] Copyright (c) 2007-2008, Realsil Wlan
[   11.006389] list_add corruption. prev->next should be next (ffffa0efc9452b30), but was 2e66c39066666666. (prev=ffffffffc0baa5c0).
[   11.006451] ------------[ cut here ]------------
[   11.006452] kernel BUG at lib/list_debug.c:28!
[   11.006457] invalid opcode: 0000 [#1] PREEMPT SMP PTI
[   11.006460] CPU: 1 PID: 283 Comm: systemd-udevd Tainted: G           OE     4.19.0-16-rt-amd64 #1 Debian 4.19.181-1

etc.  Its in the file already posted.  Thanks.

**Comment by lwfinger** [comment]
I can only compile the code, but without a real, running 4.19 system, the module does not build. Please do the following from the code directory:

gdb 8190p.ko
At the (gdb) prompt, type 'l *TSInitialize+0x2c6' without the ' marks.

Post the output. Typing quit will exit gdb.

**Comment by Crono141** [comment]
0x7d56 is in TSInitialize (/usr/src/linux-headers-4.19.0-16-common-rt/include/linux/list.h:60).
55	 */
56	static inline void __list_add(struct list_head *new,
57				      struct list_head *prev,
58				      struct list_head *next)
59	{
60		if (!__list_add_valid(new, prev, next))
61			return;
62	
63		next->prev = new;
64		new->next = next;

**Comment by lwfinger** [comment]
That inline  of __list_add kind of obscures the problem, which is that the driver is not properly initializing some of the queues that it uses. I added a couple of INIT_LIST_HEAD() calls in TSInitialize() and added some logging.

This type of failure does not give me a warm feeling about this driver!

**Comment by Crono141** [comment]
Still no joy.  Here's the dmesg.  Looks like the same error.
[dmesg.log](https://github.com/lwfinger/rtl8190p/files/6411955/dmesg.log)

(gdb) l *TSInitialize+0x2c6
0x7d56 is in GetTs (/home/joe/Build/rtl8190p/src/rtl819x_TSProc.c:302).
297		u8	dir;
298		bool	search_dir[4] = {0};
299		struct list_head *psearch_list;
300		PTS_COMMON_INFO	pRet = NULL;
301	
302		if (ieee->iw_mode == IW_MODE_MASTER) {
303			if (TxRxSelect == TX_DIR) {
304				search_dir[DIR_DOWN] = true;
305				search_dir[DIR_BI_DIR]= true;
306			} else {

**Comment by lwfinger** [comment]
I added some additional logging printouts. Run and send me dmesg.txt.

**Comment by Crono141** [comment]
Unfortunately, I lost access to the hardware today (I was setting it up for
a family member). If I get a chance to, I will continue troubleshooting,
but it may be some time. Thanks again for all your help and efforts this
weekend. Sorry we weren't able to bring it to completion.

**Comment by lwfinger** [comment]
When you get access, I will try to help. Unfortunately, I have no idea what the offending routine is trying to do. Most of the Realtek drivers have a similar structure, but the one was written in the old Realsil days. That is/was the Chinese company. Realtek is in Taiwan.
